from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ForcedDistributionScreen:
    spend: float
    player_funded_payout_fraction: float
    guaranteed_external_subsidy: float = 0.0
    guaranteed_external_capture: float = 0.0
    unavoidable_costs: float = 0.0

    def validate(self) -> None:
        if self.spend < 0:
            raise ValueError("spend cannot be negative")
        if not 0.0 <= self.player_funded_payout_fraction <= 1.0:
            raise ValueError("player_funded_payout_fraction must be in [0,1]")
        if self.guaranteed_external_subsidy < 0:
            raise ValueError("guaranteed_external_subsidy cannot be negative")
        if self.guaranteed_external_capture < 0:
            raise ValueError("guaranteed_external_capture cannot be negative")
        if self.unavoidable_costs < 0:
            raise ValueError("unavoidable_costs cannot be negative")

    @property
    def player_funded_return_upper_bound(self) -> float:
        self.validate()
        return self.spend * self.player_funded_payout_fraction

    @property
    def minimum_external_subsidy_required(self) -> float:
        """Necessary external money/capture to reach strictly positive net profit.

        This is deliberately favorable: it assumes the portfolio captures every
        unit of prize allocation generated by its own purchases. Real sharing,
        prize caps and execution can only raise the true requirement.
        """
        self.validate()
        return (
            (1.0 - self.player_funded_payout_fraction) * self.spend
            + self.unavoidable_costs
        )

    @property
    def guaranteed_external_value(self) -> float:
        self.validate()
        return self.guaranteed_external_subsidy + self.guaranteed_external_capture

    @property
    def optimistic_net_upper_bound(self) -> float:
        self.validate()
        return (
            self.player_funded_return_upper_bound
            + self.guaranteed_external_value
            - self.spend
            - self.unavoidable_costs
        )

    def passes_necessary_condition(self) -> bool:
        """Strict terminal-profit gate; passing is necessary, never sufficient."""
        return self.optimistic_net_upper_bound > 0.0


def full_space_spend(combinations: int, price_per_combination: float) -> float:
    if combinations < 0:
        raise ValueError("combinations cannot be negative")
    if price_per_combination < 0:
        raise ValueError("price_per_combination cannot be negative")
    return combinations * price_per_combination


def blended_payout_fraction(
    component_prices: list[float] | tuple[float, ...],
    payout_fractions: list[float] | tuple[float, ...],
) -> float:
    """Return price-weighted payout allocation across required components."""
    if len(component_prices) != len(payout_fractions) or not component_prices:
        raise ValueError("components must be non-empty and same length")
    if any(price < 0 for price in component_prices):
        raise ValueError("component price cannot be negative")
    if any(not 0.0 <= fraction <= 1.0 for fraction in payout_fractions):
        raise ValueError("payout fraction must be in [0,1]")
    total_price = sum(component_prices)
    if total_price <= 0:
        raise ValueError("total component price must be positive")
    return sum(
        price * fraction
        for price, fraction in zip(component_prices, payout_fractions)
    ) / total_price
