"""H227 exact cross-sector symmetry for the H225 general cyclic-affine family.

The support hypergraph is
 A={0,1,2}, B={0,3,4}, C={1,3,4}, D={2,3,4}.
Its vertex automorphism group is S3 on {0,1,2} times S2 on {3,4}, order 12.
Because all affine coefficients are odd units mod 16, reorienting any support
triple after a vertex permutation stays inside the general cyclic-affine family.

After H225 normalization, the three sole layers are encoded by the projective
triple q=(beta,gamma,1) through equations
  x4 = xi + q_i*x3,  i=0,1,2.
S3 permutes q coordinates and renormalization divides by the new q_2.
Swapping groups 3 and 4 maps q_i -> q_i^{-1}; after projective
renormalization this is inversion of the normalized triple.

Hence the 36 unordered beta<=gamma sectors fall into exact orbits under the
12-element action generated by projective S3 and inversion.
"""
from __future__ import annotations
from itertools import permutations

MOD=16
ODDS=(1,3,5,7,9,11,13,15)
SECTORS=tuple((b,g) for i,b in enumerate(ODDS) for g in ODDS[i:])


def inv(x:int)->int:
    for y in ODDS:
        if x*y % MOD == 1:
            return y
    raise ValueError(x)


def canonical_pair(b:int,g:int)->tuple[int,int]:
    return (b,g) if b<=g else (g,b)


def normalize_projective(t:tuple[int,int,int])->tuple[int,int,int]:
    z=inv(t[2])
    return (t[0]*z%MOD,t[1]*z%MOD,1)


def image(pair:tuple[int,int],perm:tuple[int,int,int],flip34:bool)->tuple[int,int]:
    q=(pair[0],pair[1],1)
    q=tuple(q[i] for i in perm)
    if flip34:
        q=tuple(inv(x) for x in q)
    q=normalize_projective(q)
    return canonical_pair(q[0],q[1])


def action_maps():
    maps=[]
    for p in permutations(range(3)):
        for flip in (False,True):
            m=tuple(image(s,p,flip) for s in SECTORS)
            assert all(x in SECTORS for x in m)
            maps.append(m)
    assert len(maps)==12
    assert len(set(maps))==12
    return tuple(maps)


def sector_orbits():
    maps=action_maps(); pos={s:i for i,s in enumerate(SECTORS)}
    seen=set(); out=[]
    for s in SECTORS:
        if s in seen: continue
        orb={m[pos[s]] for m in maps}
        # Closure sanity check under all maps.
        changed=True
        while changed:
            changed=False
            for x in tuple(orb):
                for m in maps:
                    y=m[pos[x]]
                    if y not in orb:
                        orb.add(y); changed=True
        seen.update(orb)
        out.append(tuple(sorted(orb)))
    assert len(seen)==36
    assert len(out)==11
    sizes=tuple(len(o) for o in out)
    assert sizes==(1,4,4,2,2,2,6,3,6,3,3)
    return tuple(out)


def main():
    orbits=sector_orbits()
    print('support_hypergraph_automorphism_group_size',12)
    print('raw_normalized_BC_sectors',len(SECTORS))
    print('exact_cross_sector_orbits',len(orbits))
    print('reduction_factor',len(SECTORS)/len(orbits))
    for i,o in enumerate(orbits):
        print(i,'rep',o[0],'orbit_size',len(o),'stabilizer_size',12//len(o),'orbit',o)
    # An exhaustive coefficient-pattern screen therefore needs only 11 sector
    # representatives, not 36, provided every representative is searched fully.
    raw_sector_patterns=36*45760
    rep_sector_patterns=11*45760
    print('raw_sector_coefficient_patterns',raw_sector_patterns)
    print('representative_sector_coefficient_patterns',rep_sector_patterns)
    print('sector_pattern_reduction_factor',raw_sector_patterns/rep_sector_patterns)
    assert raw_sector_patterns==1_647_360
    assert rep_sector_patterns==503_360
    print('VERIFIED')

if __name__=='__main__':
    main()
